import { chromium, devices } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await b.newContext({ ...devices['Pixel 7'], permissions:['geolocation'],
  geolocation:{latitude:37.2296,longitude:-80.4139}, baseURL:'http://127.0.0.1:8000' })
const p = await ctx.newPage()
await p.goto('/')
await p.getByLabel('First name').fill('Ada'); await p.getByLabel('Last name').fill('Walker')
await p.getByLabel('Email').fill(`shot+${Date.now()}@example.com`)
await p.screenshot({path:'/tmp/s1-register.png'})
await p.getByRole('button',{name:'Start walking'}).click()
await p.getByRole('heading',{name:/Hello/}).waitFor()
await p.screenshot({path:'/tmp/s2-home.png'})
await p.getByRole('button',{name:'Generate a Prayer Walk'}).click()
await p.screenshot({path:'/tmp/s3-location.png'})
await p.getByRole('button',{name:'Use my location'}).click()
await p.locator('.sizes').waitFor({timeout:60000})
await p.locator('.tick',{hasText:'Medium'}).click()
await p.screenshot({path:'/tmp/s4-sizes.png', fullPage:true})
await p.getByRole('button',{name:'Preview this walk'}).click()
await p.getByRole('heading',{name:'Preview your walk'}).waitFor()
await p.getByRole('button',{name:'Start this walk'}).click()
await p.getByRole('heading',{name:'Your walk'}).waitFor()
await p.screenshot({path:'/tmp/s5-active.png', fullPage:true})
await p.getByRole('button',{name:'I have finished'}).click()
await p.getByRole('heading',{name:/How did the walk go/}).waitFor()
await p.locator('.choice',{hasText:'part of it'}).click()
await p.screenshot({path:'/tmp/s6-confirm.png', fullPage:true})
await p.locator('.choice',{hasText:'as planned'}).click()
await p.getByRole('button',{name:'Record this walk'}).click()
await p.getByRole('heading',{name:'Thank you'}).waitFor({timeout:20000})
await p.getByRole('button',{name:'Back to home'}).click()
await p.getByRole('button',{name:'Progress',exact:true}).click()
await p.locator('.legend').waitFor({timeout:30000})
await p.screenshot({path:'/tmp/s7-progress.png', fullPage:true})
await b.close()
