"""phase 3.1 route feedback

Revision ID: 7ec2c3ef667b
Revises: e1ab0f225179
Create Date: 2026-08-03 03:26:15.534966
"""
from alembic import op
import sqlalchemy as sa


revision = '7ec2c3ef667b'
down_revision = 'e1ab0f225179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('walk_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('easy_to_follow', sa.Boolean(), nullable=True),
    sa.Column('time_felt_accurate', sa.Boolean(), nullable=True),
    sa.Column('had_bad_connection', sa.Boolean(), nullable=False),
    sa.Column('bad_connection_detail', sa.Text(), nullable=True),
    sa.Column('completed_as_planned', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('network_id', sa.String(length=64), nullable=False),
    sa.Column('network_version', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('coverage_area_id', sa.String(length=32), nullable=True),
    sa.Column('start_node', sa.Integer(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('submitted_from', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walk_id', name='uq_feedback_walk')
    )
    with op.batch_alter_table('route_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_feedback_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_feedback_walk_id'), ['walk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_feedback_walk_id'))
        batch_op.drop_index(batch_op.f('ix_route_feedback_participant_id'))
        batch_op.drop_index(batch_op.f('ix_route_feedback_created_at'))

    op.drop_table('route_feedback')
    # ### end Alembic commands ###
