"""phase 3 initial schema

Revision ID: e1ab0f225179
Revises: 
Create Date: 2026-08-03 03:00:38.551057
"""
from alembic import op
import sqlalchemy as sa


revision = 'e1ab0f225179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_email_normalized'), ['email_normalized'], unique=True)
        batch_op.create_index(batch_op.f('ix_participants_token_hash'), ['token_hash'], unique=True)

    op.create_table('admin_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)

    op.create_table('route_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('network_id', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('start_node', sa.Integer(), nullable=False),
    sa.Column('start_source', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('coverage_area_id', sa.String(length=32), nullable=True),
    sa.Column('component_index', sa.Integer(), nullable=True),
    sa.Column('completion_state_version', sa.String(length=64), nullable=False),
    sa.Column('requested_family', sa.String(length=16), nullable=True),
    sa.Column('active_reservation_count', sa.Integer(), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_requests_participant_id'), ['participant_id'], unique=False)

    op.create_table('walks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('network_id', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('target_miles', sa.Float(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('planned_segment_ids', sa.JSON(), nullable=False),
    sa.Column('planned_required_ids', sa.JSON(), nullable=False),
    sa.Column('planned_connector_ids', sa.JSON(), nullable=False),
    sa.Column('score_components', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('final_segment_ids', sa.JSON(), nullable=False),
    sa.Column('manual_additions', sa.JSON(), nullable=False),
    sa.Column('manual_removals', sa.JSON(), nullable=False),
    sa.Column('final_distance_miles', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('walks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_walks_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_walks_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_walks_status'), ['status'], unique=False)

    op.create_table('completions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('walk_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=16), nullable=False),
    sa.Column('network_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('via_alternative', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walk_id', 'segment_id', name='uq_completion_walk_segment')
    )
    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.create_index('ix_completion_segment', ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completions_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_completions_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completions_walk_id'), ['walk_id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('walk_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walk_id', 'segment_id', name='uq_reservation_walk_segment')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('ix_reservation_segment_expiry', ['segment_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_walk_id'), ['walk_id'], unique=False)

    op.create_table('walk_edits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('walk_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('segment_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('walk_edits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_walk_edits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_walk_edits_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_walk_edits_walk_id'), ['walk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk_edits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_walk_edits_walk_id'))
        batch_op.drop_index(batch_op.f('ix_walk_edits_participant_id'))
        batch_op.drop_index(batch_op.f('ix_walk_edits_created_at'))

    op.drop_table('walk_edits')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_walk_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_segment_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_participant_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_expires_at'))
        batch_op.drop_index('ix_reservation_segment_expiry')

    op.drop_table('reservations')
    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completions_walk_id'))
        batch_op.drop_index(batch_op.f('ix_completions_participant_id'))
        batch_op.drop_index(batch_op.f('ix_completions_completed_at'))
        batch_op.drop_index('ix_completion_segment')

    op.drop_table('completions')
    with op.batch_alter_table('walks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_walks_status'))
        batch_op.drop_index(batch_op.f('ix_walks_request_id'))
        batch_op.drop_index(batch_op.f('ix_walks_participant_id'))

    op.drop_table('walks')
    with op.batch_alter_table('route_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_requests_participant_id'))
        batch_op.drop_index(batch_op.f('ix_route_requests_created_at'))

    op.drop_table('route_requests')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_actor_id'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_token_hash'))
        batch_op.drop_index(batch_op.f('ix_participants_email_normalized'))

    op.drop_table('participants')
    # ### end Alembic commands ###
